const SHOW_ALERT = "SHOW_ALERT";
const CLEAR_ALERT = "CLEAR_ALERT";
const REGISTER_BEGIN = "REGISTER_BEGIN";
const REGISTER_SUCCESS = "REGISTER_SUCCESS";
const REGISTER_ERROR = "REGISTER_ERROR";

const Login_BEGIN = "Login_BEGIN";
const Login_SUCCESS = "Login_SUCCESS";
const Login_ERROR = "Login_ERROR";
const SHOW_SIDE_BAR ="SHOW_SIDE_BAR"
const LOGOUT ="LOGOUT"
export {
  SHOW_ALERT,
  CLEAR_ALERT,
  REGISTER_BEGIN,
  REGISTER_ERROR,
  REGISTER_SUCCESS,
  Login_BEGIN,
  Login_ERROR,
  Login_SUCCESS,
  SHOW_SIDE_BAR,
  LOGOUT
};
