const SHOW_ALERT ='SHOW_ALERT'
const CLEAR_ALERT ="CLEAR_ALERT"
const REGISTER_BEGIN ="REGISTER_BEGIN"
const REGISTER_SUCCESS ="REGISTER_SUCCESS"
const REGISTER_ERROR = "REGISTER_ERROR"
export{SHOW_ALERT ,CLEAR_ALERT ,REGISTER_BEGIN ,REGISTER_ERROR ,REGISTER_SUCCESS}